/**********************************************************************/
/* Copyright 2014 RCF                                                 */ 
/*                                                                    */
/* Licensed under the Apache License, Version 2.0 (the "License");    */
/* you may not use this file except in compliance with the License.   */
/* You may obtain a copy of the License at                            */
/*                                                                    */
/*     http://www.apache.org/licenses/LICENSE-2.0                     */
/*                                                                    */
/* Unless required by applicable law or agreed to in writing,         */
/* software distributed under the License is distributed on an        */
/* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,       */
/* either express or implied.                                         */
/* See the License for the specific language governing permissions    */
/* and limitations under the License.                                 */
/**********************************************************************/
// Generated by Flexc++ V1.03.01 on Sat, 05 Apr 2014 21:06:29 -0300

#ifndef H_POSITRON_SCANNER_INCLUDED
#define H_POSITRON_SCANNER_INCLUDED

// Scanner/Parser libraries
#include "Scannerbase.h"

namespace positron
{
    class Scanner: public ScannerBase
    {
        public:
            explicit 
            Scanner(std::istream& in  = std::cin,
                    std::ostream& out = std::cout)
                : ScannerBase(in, out) {}
            
            int lex();

        private:
            int lex__();
            int executeAction__(size_t ruleNr);
            
            void print();
            void preCode(); // re-implement this function 
                            // for code that must be exec'ed 
                            // before the patternmatching starts
    };
}

#endif
